config = {
  "aws_access_key": "",
  "aws_secret_access_key": "",
  "aws_credentials_id": "aws_credentials",
  "redshift_arn": "arn:aws:iam::374471496424:role/dwhRole",
  "redshift_db": "nbadb",
  "redshift_user": "nba_fan",
  "redshift_pswd": "wadeChampion2006",
  "redshift_host": "dwhcluster.cmctj7fg6vsy.us-east-1.redshift.amazonaws.com",
  "redshift_port": "5439",
  "redshift_conn_id": "redshift_nba",
  "s3_bucket": "de-luisitovillapun",
  "s3_shots_key": "nba/samples/sample_NBA_Shots_2000_to_2018.csv",
  "s3_players_2_key": "nba/samples/sample_Players.csv",
  "s3_players_1_key": "nba/samples/sample_player_data.csv",
  "s3_all_star_key": "nba/samples/sample_all_star.csv",
  "s3_historical_key": "nba/samples/sample_historical_nba_performance.csv",
  "skip_stage_3": False,
  "skip_stage_4": False,
  "skip_stage_5": False,
  "skip_stage_6": False,
  "skip_stage_7": False
}